# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-19 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dctuser',
            name='permission',
            field=models.IntegerField(default=1, verbose_name='\u7528\u6237\u6743\u9650(0:\u8d85\u7ea7, 1:\u67e5\u770b, 2:\u7f16\u8f91, 3:\u5220\u9664)'),
        ),
    ]
